# Generated by Django 5.1.5 on 2025-02-12 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_item_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="text",
        ),
    ]
